### ISSUE TITLE
Png file problem

### ISSUE THREAD

**Issue by ibrahimuslu** [ismailarilik/visual-python#5]
I have tested on MacOSX Mojave v10.14.5

Error is: 
```macs-MacBook-Air-4:visual-python-master mac$ python3 -m visual_python

Traceback (most recent call last):

  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)

  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code

    exec(code, run_globals)

  File "/Users/mac/Downloads/visual-python-master/visual_python/__main__.py", line 3, in <module>

    app = App()

  File "/Users/mac/Downloads/visual-python-master/visual_python/__init__.py", line 22, in __init__

    self.icon = tk.PhotoImage(file=icon_path)

  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 3545, in __init__

    Image.__init__(self, 'photo', name, cnf, master, **kw)

  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 3501, in __init__

    self.tk.call(('image', 'create', imgtype, name,) + options)

_tkinter.TclError: couldn't recognize data in image file "/Users/mac/Downloads/visual-python-master/visual_python/icons/python.png"```

**Comment by ismailarilik** [comment]
Thank you for your feedback. With Tk 8.6, PNG files are supported. What is your Tk version?

**Comment by ibrahimuslu** [comment]
tk.TkVersion 8.5 
I have updated and its opened without any problem
